#!/usr/bin/python

from to_sentry import VERSION
from sys import argv, exit

def usage():
    print """to_sentry_needs_upgrade version"

    Returns an exit code of 0 if <version> is smaller or equal to the
    current version (%(versions)s).  Returns an exit code of 1 if 
    <version? is larger than the current version (%(version)s).

    Version strings must be of the form x.y.z where x, y and z are
    decimal numbers.

""" % dict(version=VERSION)
    exit(0)

if len(argv) != 2: usage
version = tuple(map(int, argv[1].split('.')))
if len(version) != 3: usage()
if version > VERSION:
    print "Current version is %(VERSION)s and an upgrade is required to reach version %(version)s." % vars()
    exit(1)
print "Current version is %(VERSION)s and no upgrade is required." % vars()
exit(0)
